name: edgerl
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - comm=0.2.3
  - debugpy=1.8.18
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - abnf==2.2.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - backoff==2.2.1
      - certifi==2026.1.4
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - cint==1.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - diskcache==5.6.3
      - fickling==0.1.7
      - filelock==3.20.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gql==4.0.0
      - graphql-core==3.2.7
      - graphviz==0.21
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - intervaltree==3.2.1
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kaitaistruct==0.11
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.15.0
      - networkx==3.6.1
      - numpy==2.4.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - orjson==3.11.5
      - pandas==2.3.3
      - pdfminer-six==20260107
      - pillow==12.0.0
      - plotly==6.5.2
      - polyfile-weave==0.5.8
      - propcache==0.4.1
      - protobuf==6.33.4
      - pulp==3.3.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.1
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scipy==1.16.3
      - sentry-sdk==2.49.0
      - smmap==5.0.2
      - snakeviz==2.2.2
      - sortedcontainers==2.4.0
      - stdlib-list==0.11.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensordict==0.10.0
      - torch==2.9.1
      - torchrl==0.10.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - wandb==0.24.0
      - weave==0.52.24
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/vincent/miniconda3/envs/edgerl
